stages:
    - docker-build

.docker-build-test:
    stage: docker-build
    when: manual
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "{\"auths\":{\"$DOCKER_HUB\":{\"username\":\"$DOCKER_HUB_USER\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile Dockerfile --destination margrignard/shamo:test-${PY}

docker-build-test-3.5:
    extends: .docker-build-test
    variables:
        PY: "3.5"

docker-build-test-3.6:
    extends: .docker-build-test
    variables:
        PY: "3.6"

docker-build-test-3.7:
    extends: .docker-build-test
    variables:
        PY: "3.7"

docker-build-test-3.8:
    extends: .docker-build-test
    variables:
        PY: "3.8"
