image: "margrignard/shamo:latest-deps"

before_script:
    - python --version
    - python -m pip install -r requirements.txt
    - python -m pip install .

stages:
    - Static Analysis
    - Test

flake8:
    stage: Static Analysis
    script:
    - python -m pip install flake8
    - python -m flake8 --max-line-length=80 shamo

pytest:
    stage: Test
    script:
    - python -m pip install pytest
    - pytest .
