stages:
    - docker-build
    - static-test
    - integrated-test

# BUILD DOCKER TEST IMAGES ----------------------------------------------------
.docker-build-test:
    stage: docker-build
    when: manual
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "{\"auths\":{\"${DOCKER_HUB}\":{\"username\":\"${DOCKER_HUB_USER}\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - cat /kaniko/.docker/config.json
        - /kaniko/executor --cache=true --context dir:///tmp/workspace --dockerfile Dockerfile --destination ${DOCKER_HUB}/${DOCKER_HUB_USER}/shamo:test-${PY}

# Python 3.5
docker-build-test-3.5:
    extends: .docker-build-test
    variables:
        PY: "3.5"

# Python 3.6
docker-build-test-3.6:
    extends: .docker-build-test
    variables:
        PY: "3.6"

# Python 3.7
docker-build-test-3.7:
    extends: .docker-build-test
    variables:
        PY: "3.7"

# Python 3.8
docker-build-test-3.8:
    extends: .docker-build-test
    variables:
        PY: "3.8"
# STATIC TESTS ----------------------------------------------------------------
flake8:
    stage: static-test
    image: ${DOCKER_HUB_USER}/shamo:test-3.7
    script:
        - tox -e flake8

# INTEGRATED TESTS ------------------------------------------------------------
.test:
    stage: integrated-test
    image: ${DOCKER_HUB_USER}/shamo:test-${PY}
    script:
        - tox -e py${PY}

# Python 3.5
test-3.5:
    extends: .test
    variables:
        PY: "3.5"

# Python 3.6
test-3.6:
    extends: .test
    variables:
        PY: "3.6"

# Python 3.7
test-3.7:
    extends: .test
    variables:
        PY: "3.7"

# Python 3.8
test-3.8:
    extends: .test
    variables:
        PY: "3.8"
