image: "margrignard/shamo:latest-deps"

before_script:
    - python --version
    - python -m pip install -r requirements.txt
    - python -m pip install .

stages:
    - Static Analysis
    - Test

flake8:
    stage: Static Analysis
    script:
    - python -m pip install flake8
    - python -m flake8 --max-line-length=80 shamo

py34-pytest:
    stage: Test
    script:
    - pip install tox
    - tox -e py34

py35-pytest:
    stage: Test
    script:
    - pip install tox
    - tox -e py35

py36-pytest:
    stage: Test
    script:
    - pip install tox
    - tox -e py36

py37-pytest:
    stage: Test
    script:
    - pip install tox
    - tox -e py37

py38-pytest:
    stage: Test
    script:
    - pip install tox
    - tox -e py38
