name: Docker Image Tag

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: tagName
      uses: olegtarasov/get-tag@v2

    - name: Build Build and publish "python" image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: margrignard/shamo
        tags: python-${{ steps.tagName.outputs.tag }}
        target: python
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: Build Build and publish "jupyter" image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: margrignard/shamo
        tags: jupyter-${{ steps.tagName.outputs.tag }}
        target: jupyter
        cache_froms: margrignard/shamo:python-${{ steps.tagName.outputs.tag }}
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
